[package]
name = "cargo-wheel"
version = "0.1.0"
authors = ["Markus Klein <markus-klein@live.de>"]
publish = false
license = "MIT"

[dependencies]
cargo = "0.30"
env_logger = "0.5"
structopt = "0.2"
cbindgen = "0.6"
mustache = "0.9"
serde = "1.0"
serde_derive = "1.0"
pathdiff = "0.1"